apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : application2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: application2
  source:
    path   : "helm_charts/DemoChart_02"
    repoURL: "git@github.com:zuFrost/zizi_k8s_sept_argocd.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values_dev.yaml
      parameters:
      - name: "container.image"
        value: zufrost/zizi_k8s_sept_html:version2

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    
