apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : kubernetes-metrics-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: metrics-server
  source:
    path   : "helm_charts/kubernetes-metrics-server"
    repoURL: "git@github.com:zuFrost/zizi_k8s_sept_argocd.git"
    targetRevision: HEAD
    helm:
#      valueFiles:
#      - values_dev.yaml
      parameters:
#      - name: "container.image"
#        value: zufrost/zizi_k8s_sept_html:version1

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    
